'''
Convert the trajectory of the Lorenz attractor generated by the KalmanNet program from a ".pt" file to a ".npy" file.
'''

import numpy as np
import torch

device = torch.device('cpu')
dir = 'part_f/0dB'

[train_input_long,train_target_long, cv_input, cv_target, test_input, test_target,_,_,_] =  torch.load('data/%s/data_lor_v20_rq1030_T100.pt'%dir, map_location=device)
print(test_input.size())
print(test_target.size())
train_input_long = torch.transpose(train_input_long,dim0=1,dim1=2).cpu().numpy()
train_target_long = torch.transpose(train_target_long,dim0=1,dim1=2).cpu().numpy()
test_input_long = torch.transpose(test_input,dim0=1,dim1=2).cpu().numpy()
test_target_long = torch.transpose(test_target,dim0=1,dim1=2).cpu().numpy()
# print(train_input_long)
# print(train_target_long)
train_data = np.concatenate([train_input_long,train_target_long],axis=2)
print('Train',train_data.shape)
test_data = np.concatenate([test_input_long,test_target_long],axis=2)
print('Test',test_data.shape)
np.save('data/%s/Train_data.npy'%dir,train_data)
np.save('data/%s/Test_data.npy'%dir,test_data)


